#!/bin/bash

if [ "$#" -ne 1 ]; then
	input="target/Dockerfile"
else
	input=${1}
fi

# use absolute path of scripts as later eval might change the working dir
joiner=$(readlink -e src/multiline_joiner.awk)
parser=$(readlink -e src/docker_cmd_parser.awk)

awk -f ${joiner} ${input} | while read line
do
	bash_line=$(echo $line | awk -f ${parser})
	echo ""
	echo "$line"
	echo "$bash_line"
	eval $bash_line
done