#!/bin/bash

if [ "$#" -ne 1 ]; then
	input="target/Dockerfile"
else
	input=${1}
fi

awk -f multiline_joiner.awk ${input} | while read line
do
	bash_line=$(echo $line | awk -f docker_cmd_parser.awk)
	echo ""
	echo "$line"
	eval $bash_line
done